"""añade imagen al modelo post

Revision ID: 09c282dbd740
Revises: a1dcb5ef331b
Create Date: 2022-01-29 15:52:02.585960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c282dbd740'
down_revision = 'a1dcb5ef331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_name')
    # ### end Alembic commands ###
