"""añade imagen al modelo user

Revision ID: 1907ea007fb0
Revises: 09c282dbd740
Create Date: 2022-01-29 16:57:30.528444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1907ea007fb0'
down_revision = '09c282dbd740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_user', 'image_name')
    # ### end Alembic commands ###
