"""empty message

Revision ID: 2f590722713a
Revises: 81e37351f4b4
Create Date: 2022-08-27 21:37:16.239854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f590722713a'
down_revision = '81e37351f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cart',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shopping_cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_cart.id'], name='user_cart_shopping_cart_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], name='user_cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_id', 'shopping_cart_id', name='user_cart_pkey')
    )
    # ### end Alembic commands ###
