"""empty message

Revision ID: 3d2781bb20bc
Revises: e1b73b3cae69
Create Date: 2022-08-27 20:48:58.338442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d2781bb20bc'
down_revision = 'e1b73b3cae69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cart',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_cart.id'], name='user_cart_cart_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], name='user_cart_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'cart_id', name='user_cart_pkey')
    )
    # ### end Alembic commands ###
