"""empty message

Revision ID: 945f24f23676
Revises: 8e42d563d569
Create Date: 2022-08-26 22:47:02.321258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945f24f23676'
down_revision = '8e42d563d569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
